### ISSUE TITLE
Missing go.mod file

### ISSUE THREAD

**Issue by thomasvvugt** [dgrr/fastws#10]
Hi @dgrr 
Awesome work on this repository. Could you add a go.mod file to this repository as well as [fasthttp/fastws](https://github.com/fasthttp/fastws)?
Thanks!

**Comment by thomasvvugt** [comment]
Awesome, could you also tag versions on both repositories? Really much appreciated!

**Comment by dgrr** [comment]
Hello,

I released a version `v1.0`. Thanks.
