### ISSUE TITLE
panic: runtime error: slice bounds out of range [:18446744073709551615] with capacity 12288

### ISSUE THREAD

**Issue by onoketa** [dgrr/fastws#11]
goroutine 45 [running]:
github.com/dgrr/fastws.(*Frame).readFrom(0xc000164620, 0xec87e0, 0xc0007a3710, 0x6c, 0x0, 0x0)
        /home/onoketa/go/src/github.com/iyouport-org/relaybaton/vendor/github.com/dgrr/fastws/frame.go:522 +0x72c
github.com/dgrr/fastws.(*Frame).ReadFrom(...)
        /home/onoketa/go/src/github.com/iyouport-org/relaybaton/vendor/github.com/dgrr/fastws/frame.go:456
github.com/dgrr/fastws.(*Conn).readLoop(0xc000174f50)
        /home/onoketa/go/src/github.com/iyouport-org/relaybaton/vendor/github.com/dgrr/fastws/conn.go:167 +0x112
created by github.com/dgrr/fastws.(*Conn).Reset
        /home/onoketa/go/src/github.com/iyouport-org/relaybaton/vendor/github.com/dgrr/fastws/conn.go:156 +0x22a

**Comment by dgrr** [comment]
Hello @onoketa 

I am trying to recreate the error. I know it's happening because there's an overflow, but I would like to know if you can tell me, which type of WebSocket packet did you received to get the error?

Thank you.

**Comment by dgrr** [comment]
Got it @onoketa 

You are getting a `close` message with some kind of garbage info. I wasn't aware of the uint64 overflow.

Thank you for reporting it.
